
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f23/team03-f23-6pm-1
owner: ucsb-cs156-f23
repo_name: team03-f23-6pm-1
pull_requests: [{"author":{"id":"MDQ6VXNlcjQyMTYzMjQx","is_bot":false,"login":"jakedel","name":"Jake Delgado"},"headRefName":"jake-edit","number":91,"title":"Add edit page for UCSBDiningCommonsMenuItem plus tests and stories","url":"https://github.com/ucsb-cs156-f23/team03-f23-6pm-1/pull/91"},{"author":{"id":"MDQ6VXNlcjQ0Njg5MjQw","is_bot":false,"login":"Johnsonchan105","name":"Johnson Chan"},"headRefName":"NewBranchJohnson","number":89,"title":"Finished Create Page for UCSBOrganization","url":"https://github.com/ucsb-cs156-f23/team03-f23-6pm-1/pull/89"}]
