
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f23/team03-f23-6pm-1
owner: ucsb-cs156-f23
repo_name: team03-f23-6pm-1
pull_requests: [{"author":{"id":"U_kgDOBXj-Bg","is_bot":false,"login":"chauAlex","name":""},"headRefName":"Alex-CreatePageRecommendationRequest","number":73,"title":"Create Page for RecommendationRequest and adjustments to navigation endpoints","url":"https://github.com/ucsb-cs156-f23/team03-f23-6pm-1/pull/73"},{"author":{"id":"U_kgDOBXj-Bg","is_bot":false,"login":"chauAlex","name":""},"headRefName":"Alex-PlaceholderRecommendationRequest","number":72,"title":"Placeholders for RecommendationRequest Create/Edit/Index pages","url":"https://github.com/ucsb-cs156-f23/team03-f23-6pm-1/pull/72"},{"author":{"id":"MDQ6VXNlcjM2NDk0MTY3","is_bot":false,"login":"ErwanDev","name":"Erwan"},"headRefName":"Erwan-HelpRequestPlaceholders","number":67,"title":"Placeholders for Help Requests Page","url":"https://github.com/ucsb-cs156-f23/team03-f23-6pm-1/pull/67"}]
